export const initCircles = [
  {
    index: 0,
    radius: 0.5,
    angle: 0,
    startAngle: 0,
    direction: 'cw',
    speed: 0.5,
    origin: [0, 0, 0],
    endEffector: [0, 0, 0],
  },
  {
    index: 1,
    parentIndex: 0,
    radius: 1,
    angle: 90,
    startAngle: 0,
    direction: 'cw',
    speed: 0.5,
    origin: [0, 0, 0],
    endEffector: [0, 0, 0],
  },
  {
    index: 2,
    parentIndex: 1,
    radius: 0.5,
    angle: 230,
    startAngle: 0,
    direction: 'acw',
    speed: 2.2,
    origin: [0, 0, 0],
    endEffector: [0, 0, 0],
  },
]

export const defaultGear = {
  index: 0,
  radius: 1,
  angle: 0,
  startAngle: 0,
  direction: 'cw',
  speed: 1,
  origin: [0, 0, 0],
  endEffector: [0, 0, 0],
}

export const presets = [
  {
    name: 'Default',
    circles: initCircles,
  },
  {
    name: 'Wide man',
    circles: [
      {
        index: 0,
        radius: 1,
        angle: 0,
        startAngle: 90,
        direction: 'cw',
        speed: 0.5,
        origin: [0, 0, 0],
        endEffector: [0, 0, 0],
      },
      {
        index: 1,
        parentIndex: 0,
        radius: 0.5,
        angle: 90,
        startAngle: 0,
        direction: 'acw',
        speed: 2,
        origin: [0, 0, 0],
        endEffector: [0, 0, 0],
      },
      {
        index: 2,
        parentIndex: 1,
        radius: 0.3,
        angle: 0,
        startAngle: 90,
        direction: 'cw',
        speed: 1,
        origin: [0, 0, 0],
        endEffector: [0, 0, 0],
      },
    ],
  },
  {
    name: '5 Point star',
    circles: [
      {
        index: 0,
        radius: 0.5,
        angle: 0,
        startAngle: 198,
        direction: 'cw',
        speed: 1,
        origin: [0, 0, 0],
        endEffector: [0, 0, 0],
      },
      {
        index: 1,
        parentIndex: 0,
        radius: 0.5,
        angle: 0,
        startAngle: 198,
        direction: 'acw',
        speed: 1.5,
        origin: [0, 0, 0],
        endEffector: [0, 0, 0],
      },
      {
        index: 2,
        parentIndex: 1,
        radius: 0.4,
        angle: 0,
        startAngle: 198,
        direction: 'cw',
        speed: 1,
        origin: [0, 0, 0],
        endEffector: [0, 0, 0],
      },
    ],
  },
  {
    name: 'Manta ray',
    circles: [
      {
        index: 0,
        radius: 0.5,
        angle: 0,
        startAngle: 0,
        direction: 'cw',
        speed: 1,
        origin: [0, 0, 0],
        endEffector: [0, 0, 0],
      },
      {
        index: 1,
        parentIndex: 0,
        radius: 0.5,
        angle: 0,
        startAngle: 0,
        direction: 'acw',
        speed: 2,
        origin: [0, 0, 0],
        endEffector: [0, 0, 0],
      },
      {
        index: 2,
        parentIndex: 1,
        radius: 2.4,
        angle: 0,
        startAngle: 90,
        direction: 'cw',
        speed: 0.5,
        origin: [0, 0, 0],
        endEffector: [0, 0, 0],
      },
    ],
  },
  {
    name: 'Neat bow',
    circles: [
      {
        index: 0,
        radius: 0.5,
        angle: 0,
        startAngle: 0,
        direction: 'cw',
        speed: 0.5,
        origin: [0, 0, 0],
        endEffector: [0, 0, 0],
      },
      {
        index: 1,
        parentIndex: 0,
        radius: 0.5,
        angle: 0,
        startAngle: 0,
        direction: 'acw',
        speed: 1.5,
        origin: [0, 0, 0],
        endEffector: [0, 0, 0],
      },
      {
        index: 2,
        parentIndex: 1,
        radius: 0.08,
        angle: 0,
        startAngle: 0,
        direction: 'cw',
        speed: 4,
        origin: [0, 0, 0],
        endEffector: [0, 0, 0],
      },
    ],
  },
  {
    name: 'Classic',
    circles: [
      {
        index: 0,
        radius: 2,
        angle: 0,
        startAngle: 0,
        direction: 'cw',
        speed: 4,
        origin: [0, 0, 0],
        endEffector: [0, 0, 0],
      },
      {
        index: 1,
        parentIndex: 0,
        radius: 1,
        angle: 0,
        startAngle: 0,
        direction: 'acw',
        speed: 4.48,
        origin: [0, 0, 0],
        endEffector: [0, 0, 0],
      },
    ],
  },
]
